// <auto-generated />
namespace TestDateBase.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class recreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202310100946457_recreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
